const encoder = new TextEncoder();
const decoder = new TextDecoder();

function bytesToBase64(bytes: Uint8Array) {
  let binary = '';
  bytes.forEach((byte) => { binary += String.fromCharCode(byte); });
  return btoa(binary);
}

function base64ToBytes(value: string) {
  const binary = atob(value.replace(/\s/g, ''));
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

export function bytesToHex(bytes: Uint8Array) {
  return [...bytes].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}

export function hexToBytes(value: string) {
  const normalized = value.trim().replace(/^0x/, '');
  if (!/^[0-9a-f]+$/i.test(normalized) || normalized.length % 2 !== 0) {
    throw new Error('The key must be an even-length hexadecimal value.');
  }
  return Uint8Array.from(normalized.match(/.{2}/g) ?? [], (byte) => Number.parseInt(byte, 16));
}

export function randomHex(length = 32) {
  return bytesToHex(crypto.getRandomValues(new Uint8Array(length)));
}

export async function digestText(value: string, algorithm: 'SHA-256' | 'SHA-384' | 'SHA-512') {
  const digest = await crypto.subtle.digest(algorithm, encoder.encode(value));
  return bytesToHex(new Uint8Array(digest));
}

export async function hmacSha256(value: string, secret: string) {
  if (!secret) throw new Error('Add an HMAC secret before generating a signature.');
  const key = await crypto.subtle.importKey(
    'raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign'],
  );
  const signature = await crypto.subtle.sign('HMAC', key, encoder.encode(value));
  return bytesToHex(new Uint8Array(signature));
}

type AesAlgorithm = 'AES-GCM' | 'AES-CBC';

type AesEnvelope = {
  version: 1;
  algorithm: AesAlgorithm;
  keySize: 256;
  iv: string;
  ciphertext: string;
};

async function importAesKey(keyHex: string, algorithm: AesAlgorithm, usage: KeyUsage) {
  const bytes = hexToBytes(keyHex);
  if (bytes.byteLength !== 32) throw new Error('AES-256 requires a 64-character hexadecimal key.');
  return crypto.subtle.importKey('raw', bytes, { name: algorithm }, false, [usage]);
}

export async function encryptAes(value: string, keyHex: string, algorithm: AesAlgorithm) {
  const key = await importAesKey(keyHex, algorithm, 'encrypt');
  const iv = crypto.getRandomValues(new Uint8Array(algorithm === 'AES-GCM' ? 12 : 16));
  const ciphertext = await crypto.subtle.encrypt({ name: algorithm, iv }, key, encoder.encode(value));
  const envelope: AesEnvelope = {
    version: 1,
    algorithm,
    keySize: 256,
    iv: bytesToBase64(iv),
    ciphertext: bytesToBase64(new Uint8Array(ciphertext)),
  };
  return JSON.stringify(envelope, null, 2);
}

export async function decryptAes(value: string, keyHex: string, expectedAlgorithm: AesAlgorithm) {
  const envelope = JSON.parse(value) as Partial<AesEnvelope>;
  if (envelope.version !== 1 || envelope.algorithm !== expectedAlgorithm || !envelope.iv || !envelope.ciphertext) {
    throw new Error(`Paste a valid ${expectedAlgorithm} envelope generated by this tool.`);
  }
  const key = await importAesKey(keyHex, expectedAlgorithm, 'decrypt');
  const plaintext = await crypto.subtle.decrypt(
    { name: expectedAlgorithm, iv: base64ToBytes(envelope.iv) },
    key,
    base64ToBytes(envelope.ciphertext),
  );
  return decoder.decode(plaintext);
}

function arrayBufferToPem(buffer: ArrayBuffer, label: string) {
  const base64 = bytesToBase64(new Uint8Array(buffer));
  const lines = base64.match(/.{1,64}/g)?.join('\n') ?? base64;
  return `-----BEGIN ${label}-----\n${lines}\n-----END ${label}-----`;
}

function pemToBytes(value: string, label: string) {
  const normalized = value
    .replace(`-----BEGIN ${label}-----`, '')
    .replace(`-----END ${label}-----`, '')
    .replace(/\s/g, '');
  if (!normalized) throw new Error(`Paste a valid ${label.toLowerCase()} PEM value.`);
  return base64ToBytes(normalized);
}

export async function generateRsaKeyPair() {
  const keyPair = await crypto.subtle.generateKey(
    { name: 'RSA-OAEP', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' },
    true,
    ['encrypt', 'decrypt'],
  );
  const [publicKey, privateKey] = await Promise.all([
    crypto.subtle.exportKey('spki', keyPair.publicKey),
    crypto.subtle.exportKey('pkcs8', keyPair.privateKey),
  ]);
  return {
    publicKey: arrayBufferToPem(publicKey, 'PUBLIC KEY'),
    privateKey: arrayBufferToPem(privateKey, 'PRIVATE KEY'),
  };
}

export async function encryptRsa(value: string, publicKeyPem: string) {
  const key = await crypto.subtle.importKey(
    'spki', pemToBytes(publicKeyPem, 'PUBLIC KEY'), { name: 'RSA-OAEP', hash: 'SHA-256' }, false, ['encrypt'],
  );
  const plaintext = encoder.encode(value);
  if (plaintext.byteLength > 190) throw new Error('RSA-OAEP 2048 / SHA-256 accepts at most 190 UTF-8 bytes. Use RSA to wrap an AES key for larger data.');
  const ciphertext = await crypto.subtle.encrypt({ name: 'RSA-OAEP' }, key, plaintext);
  return bytesToBase64(new Uint8Array(ciphertext));
}

export async function decryptRsa(value: string, privateKeyPem: string) {
  const key = await crypto.subtle.importKey(
    'pkcs8', pemToBytes(privateKeyPem, 'PRIVATE KEY'), { name: 'RSA-OAEP', hash: 'SHA-256' }, false, ['decrypt'],
  );
  const plaintext = await crypto.subtle.decrypt({ name: 'RSA-OAEP' }, key, base64ToBytes(value));
  return decoder.decode(plaintext);
}

export async function derivePbkdf2(passphrase: string, salt: string, iterations: number) {
  if (!passphrase || !salt) throw new Error('PBKDF2 requires both a passphrase and a salt.');
  if (!Number.isInteger(iterations) || iterations < 10_000 || iterations > 2_000_000) {
    throw new Error('Use between 10,000 and 2,000,000 iterations.');
  }
  const material = await crypto.subtle.importKey('raw', encoder.encode(passphrase), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', hash: 'SHA-256', salt: encoder.encode(salt), iterations },
    material,
    256,
  );
  return bytesToHex(new Uint8Array(bits));
}
